// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			shift(3), // MATCH
			nil,      // (
			nil,      // id
			nil,      // :
			nil,      // upid
			nil,      // )
			nil,      // -
			nil,      // [
			nil,      // ]
			nil,      // >
			nil,      // *
			nil,      // int
			nil,      // .
			nil,      // <
			nil,      // RETURN
			nil,      // ,
			nil,      // AS
			nil,      // GROUP
			nil,      // BY
			nil,      // ORDER
			nil,      // ASC
			nil,      // DESC
			nil,      // LIMIT
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // MATCH
			nil,          // (
			nil,          // id
			nil,          // :
			nil,          // upid
			nil,          // )
			nil,          // -
			nil,          // [
			nil,          // ]
			nil,          // >
			nil,          // *
			nil,          // int
			nil,          // .
			nil,          // <
			nil,          // RETURN
			nil,          // ,
			nil,          // AS
			nil,          // GROUP
			nil,          // BY
			nil,          // ORDER
			nil,          // ASC
			nil,          // DESC
			nil,          // LIMIT
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // MATCH
			nil,      // (
			nil,      // id
			nil,      // :
			nil,      // upid
			nil,      // )
			nil,      // -
			nil,      // [
			nil,      // ]
			nil,      // >
			nil,      // *
			nil,      // int
			nil,      // .
			nil,      // <
			shift(5), // RETURN
			nil,      // ,
			nil,      // AS
			nil,      // GROUP
			nil,      // BY
			nil,      // ORDER
			nil,      // ASC
			nil,      // DESC
			nil,      // LIMIT
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // MATCH
			shift(8), // (
			nil,      // id
			nil,      // :
			nil,      // upid
			nil,      // )
			nil,      // -
			nil,      // [
			nil,      // ]
			nil,      // >
			nil,      // *
			nil,      // int
			nil,      // .
			nil,      // <
			nil,      // RETURN
			nil,      // ,
			nil,      // AS
			nil,      // GROUP
			nil,      // BY
			nil,      // ORDER
			nil,      // ASC
			nil,      // DESC
			nil,      // LIMIT
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			shift(12), // GROUP
			nil,       // BY
			shift(13), // ORDER
			nil,       // ASC
			nil,       // DESC
			shift(14), // LIMIT
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(15), // id
			nil,       // :
			shift(16), // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			reduce(9), // RETURN, reduce: MatchClause
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(20), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			shift(21), // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(22), // id
			nil,       // :
			nil,       // upid
			shift(23), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			shift(13), // ORDER
			nil,       // ASC
			nil,       // DESC
			shift(14), // LIMIT
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			shift(14), // LIMIT
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			shift(27), // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			shift(28), // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			shift(29), // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(33), // ␚, reduce: ReturnItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			shift(30),  // .
			nil,        // <
			nil,        // RETURN
			reduce(33), // ,, reduce: ReturnItem
			nil,        // AS
			reduce(33), // GROUP, reduce: ReturnItem
			nil,        // BY
			reduce(33), // ORDER, reduce: ReturnItem
			nil,        // ASC
			nil,        // DESC
			reduce(33), // LIMIT, reduce: ReturnItem
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			shift(31), // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(26), // ␚, reduce: ReturnClause
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			shift(32),  // ,
			nil,        // AS
			reduce(26), // GROUP, reduce: ReturnClause
			nil,        // BY
			reduce(26), // ORDER, reduce: ReturnClause
			nil,        // ASC
			nil,        // DESC
			reduce(26), // LIMIT, reduce: ReturnClause
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(27), // ␚, reduce: ReturnItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(27), // ,, reduce: ReturnItems
			nil,        // AS
			reduce(27), // GROUP, reduce: ReturnItems
			nil,        // BY
			reduce(27), // ORDER, reduce: ReturnItems
			nil,        // ASC
			nil,        // DESC
			reduce(27), // LIMIT, reduce: ReturnItems
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			shift(34), // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			shift(35), // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(36), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			shift(37), // :
			nil,       // upid
			shift(38), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			reduce(13), // -, reduce: Node
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			reduce(13), // <, reduce: Node
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			shift(14), // LIMIT
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(40), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(43), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(44), // ␚, reduce: LimitClause
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(46), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(47), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(15), // id
			nil,       // :
			shift(16), // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			reduce(10), // RETURN, reduce: PathPattern
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(49), // id
			nil,       // :
			nil,       // upid
			shift(50), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			shift(51), // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(52), // ]
			nil,       // >
			shift(53), // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			shift(54), // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			shift(55), // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			reduce(12), // -, reduce: Node
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			reduce(12), // <, reduce: Node
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: Query
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			shift(56), // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(34), // ␚, reduce: GroupByClause
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			shift(57),  // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			reduce(34), // ORDER, reduce: GroupByClause
			nil,        // ASC
			nil,        // DESC
			reduce(34), // LIMIT, reduce: GroupByClause
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(35), // ␚, reduce: GroupByItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(35), // ,, reduce: GroupByItems
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			reduce(35), // ORDER, reduce: GroupByItems
			nil,        // ASC
			nil,        // DESC
			reduce(35), // LIMIT, reduce: GroupByItems
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(43), // ␚, reduce: OrderByItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(43), // ,, reduce: OrderByItem
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			shift(58),  // ASC
			shift(59),  // DESC
			reduce(43), // LIMIT, reduce: OrderByItem
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(38), // ␚, reduce: OrderByClause
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			shift(60),  // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			reduce(38), // LIMIT, reduce: OrderByClause
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(39), // ␚, reduce: OrderByItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(39), // ,, reduce: OrderByItems
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			reduce(39), // LIMIT, reduce: OrderByItems
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(32), // ␚, reduce: ReturnItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(32), // ,, reduce: ReturnItem
			shift(61),  // AS
			reduce(32), // GROUP, reduce: ReturnItem
			nil,        // BY
			reduce(32), // ORDER, reduce: ReturnItem
			nil,        // ASC
			nil,        // DESC
			reduce(32), // LIMIT, reduce: ReturnItem
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			shift(62), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(28), // ␚, reduce: ReturnItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(28), // ,, reduce: ReturnItems
			nil,        // AS
			reduce(28), // GROUP, reduce: ReturnItems
			nil,        // BY
			reduce(28), // ORDER, reduce: ReturnItems
			nil,        // ASC
			nil,        // DESC
			reduce(28), // LIMIT, reduce: ReturnItems
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			shift(63), // :
			nil,       // upid
			shift(64), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			reduce(13), // RETURN, reduce: Node
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(65), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(66), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			shift(67), // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			shift(68), // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			shift(69), // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			shift(70), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(71), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(40), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(41), // ␚, reduce: OrderByItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(41), // ,, reduce: OrderByItem
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			reduce(41), // LIMIT, reduce: OrderByItem
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(42), // ␚, reduce: OrderByItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(42), // ,, reduce: OrderByItem
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			reduce(42), // LIMIT, reduce: OrderByItem
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(43), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(74), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(30), // ␚, reduce: ReturnItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(30), // ,, reduce: ReturnItem
			shift(75),  // AS
			reduce(30), // GROUP, reduce: ReturnItem
			nil,        // BY
			reduce(30), // ORDER, reduce: ReturnItem
			nil,        // ASC
			nil,        // DESC
			reduce(30), // LIMIT, reduce: ReturnItem
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			shift(76), // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			reduce(12), // RETURN, reduce: Node
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(77), // ]
			nil,       // >
			shift(78), // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(25), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			shift(79),  // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(80), // ]
			nil,       // >
			nil,       // *
			nil,       // int
			shift(81), // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(82), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			shift(83), // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			reduce(11), // -, reduce: Node
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			reduce(11), // <, reduce: Node
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(37), // ␚, reduce: GroupByItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(37), // ,, reduce: GroupByItem
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			reduce(37), // ORDER, reduce: GroupByItem
			nil,        // ASC
			nil,        // DESC
			reduce(37), // LIMIT, reduce: GroupByItem
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(36), // ␚, reduce: GroupByItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(36), // ,, reduce: GroupByItems
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			reduce(36), // ORDER, reduce: GroupByItems
			nil,        // ASC
			nil,        // DESC
			reduce(36), // LIMIT, reduce: GroupByItems
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(40), // ␚, reduce: OrderByItems
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(40), // ,, reduce: OrderByItems
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			reduce(40), // LIMIT, reduce: OrderByItems
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(31), // ␚, reduce: ReturnItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(31), // ,, reduce: ReturnItem
			nil,        // AS
			reduce(31), // GROUP, reduce: ReturnItem
			nil,        // BY
			reduce(31), // ORDER, reduce: ReturnItem
			nil,        // ASC
			nil,        // DESC
			reduce(31), // LIMIT, reduce: ReturnItem
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			shift(84), // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			shift(85), // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(86), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			shift(87), // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(24), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(88), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			shift(89), // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(90), // ]
			nil,       // >
			shift(91), // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(92), // ]
			nil,       // >
			nil,       // *
			nil,       // int
			shift(93), // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(29), // ␚, reduce: ReturnItem
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			reduce(29), // ,, reduce: ReturnItem
			nil,        // AS
			reduce(29), // GROUP, reduce: ReturnItem
			nil,        // BY
			reduce(29), // ORDER, reduce: ReturnItem
			nil,        // ASC
			nil,        // DESC
			reduce(29), // LIMIT, reduce: ReturnItem
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			reduce(11), // RETURN, reduce: Node
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			shift(94), // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			shift(95), // ]
			nil,       // >
			nil,       // *
			nil,       // int
			shift(96), // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			shift(97), // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			nil,       // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			shift(98), // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // MATCH
			nil,       // (
			nil,       // id
			nil,       // :
			nil,       // upid
			nil,       // )
			shift(99), // -
			nil,       // [
			nil,       // ]
			nil,       // >
			nil,       // *
			nil,       // int
			nil,       // .
			nil,       // <
			nil,       // RETURN
			nil,       // ,
			nil,       // AS
			nil,       // GROUP
			nil,       // BY
			nil,       // ORDER
			nil,       // ASC
			nil,       // DESC
			nil,       // LIMIT
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			shift(100), // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(101), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			shift(102), // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(14), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(103), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			shift(104), // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(18), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			shift(105), // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(19), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			shift(106), // ]
			nil,        // >
			nil,        // *
			nil,        // int
			shift(107), // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(23), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			shift(108), // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			shift(109), // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			shift(110), // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(111), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(112), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			shift(113), // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			shift(114), // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(16), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			shift(115), // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			shift(116), // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(21), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			shift(117), // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(118), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(119), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(17), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			shift(120), // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(22), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			shift(121), // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			nil,        // (
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			shift(122), // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(15), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // MATCH
			reduce(20), // (, reduce: Edge
			nil,        // id
			nil,        // :
			nil,        // upid
			nil,        // )
			nil,        // -
			nil,        // [
			nil,        // ]
			nil,        // >
			nil,        // *
			nil,        // int
			nil,        // .
			nil,        // <
			nil,        // RETURN
			nil,        // ,
			nil,        // AS
			nil,        // GROUP
			nil,        // BY
			nil,        // ORDER
			nil,        // ASC
			nil,        // DESC
			nil,        // LIMIT
		},
	},
}
