// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/wouteroostervld/chainsaw/pkg/cypher/ast"

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String:     `S' : Query	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause GroupByClause OrderByClause LimitClause	<< ast.NewQueryWithClauses(X[0], X[1], X[2], X[3], X[4]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], X[2], X[3], X[4])
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause GroupByClause OrderByClause	<< ast.NewQueryWithClauses(X[0], X[1], X[2], X[3], nil) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      2,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], X[2], X[3], nil)
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause GroupByClause LimitClause	<< ast.NewQueryWithClauses(X[0], X[1], X[2], nil, X[3]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      3,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], X[2], nil, X[3])
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause OrderByClause LimitClause	<< ast.NewQueryWithClauses(X[0], X[1], nil, X[2], X[3]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      4,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], nil, X[2], X[3])
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause GroupByClause	<< ast.NewQueryWithClauses(X[0], X[1], X[2], nil, nil) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      5,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], X[2], nil, nil)
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause OrderByClause	<< ast.NewQueryWithClauses(X[0], X[1], nil, X[2], nil) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      6,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], nil, X[2], nil)
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause LimitClause	<< ast.NewQueryWithClauses(X[0], X[1], nil, nil, X[2]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      7,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQueryWithClauses(X[0], X[1], nil, nil, X[2])
		},
	},
	ProdTabEntry{
		String:     `Query : MatchClause ReturnClause	<< ast.NewQuery(X[0], X[1]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      8,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewQuery(X[0], X[1])
		},
	},
	ProdTabEntry{
		String:     `MatchClause : "MATCH" PathPattern	<< ast.NewMatchClause(X[1]) >>`,
		Id:         "MatchClause",
		NTType:     2,
		Index:      9,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewMatchClause(X[1])
		},
	},
	ProdTabEntry{
		String:     `PathPattern : Node Edge Node	<< ast.NewPathPattern(X[0], X[1], X[2]) >>`,
		Id:         "PathPattern",
		NTType:     3,
		Index:      10,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewPathPattern(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
		String:     `Node : "(" id ":" upid ")"	<< ast.NewNodeLabeled(X[1], X[3]) >>`,
		Id:         "Node",
		NTType:     4,
		Index:      11,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewNodeLabeled(X[1], X[3])
		},
	},
	ProdTabEntry{
		String:     `Node : "(" id ")"	<< ast.NewNodeVar(X[1]) >>`,
		Id:         "Node",
		NTType:     4,
		Index:      12,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewNodeVar(X[1])
		},
	},
	ProdTabEntry{
		String:     `Node : "(" ")"	<< ast.NewNodeAnon() >>`,
		Id:         "Node",
		NTType:     4,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewNodeAnon()
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" ":" id "]" "-" ">"	<< ast.NewEdgeForward(X[3]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      14,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeForward(X[3])
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" ":" id "*" int "." "." int "]" "-" ">"	<< ast.NewEdgeMultiHopForward(X[3], X[5], X[8]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      15,
		NumSymbols: 12,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopForward(X[3], X[5], X[8])
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" ":" id "*" int "]" "-" ">"	<< ast.NewEdgeMultiHopForward(X[3], X[5], X[5]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      16,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopForward(X[3], X[5], X[5])
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" "*" int "." "." int "]" "-" ">"	<< ast.NewEdgeMultiHopForward(nil, X[3], X[6]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      17,
		NumSymbols: 10,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopForward(nil, X[3], X[6])
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" "*" int "]" "-" ">"	<< ast.NewEdgeMultiHopForward(nil, X[3], X[3]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      18,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopForward(nil, X[3], X[3])
		},
	},
	ProdTabEntry{
		String:     `Edge : "<" "-" "[" ":" id "]" "-"	<< ast.NewEdgeBackward(X[4]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      19,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeBackward(X[4])
		},
	},
	ProdTabEntry{
		String:     `Edge : "<" "-" "[" ":" id "*" int "." "." int "]" "-"	<< ast.NewEdgeMultiHopBackward(X[4], X[6], X[9]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      20,
		NumSymbols: 12,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopBackward(X[4], X[6], X[9])
		},
	},
	ProdTabEntry{
		String:     `Edge : "<" "-" "[" ":" id "*" int "]" "-"	<< ast.NewEdgeMultiHopBackward(X[4], X[6], X[6]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      21,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopBackward(X[4], X[6], X[6])
		},
	},
	ProdTabEntry{
		String:     `Edge : "<" "-" "[" "*" int "." "." int "]" "-"	<< ast.NewEdgeMultiHopBackward(nil, X[4], X[7]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      22,
		NumSymbols: 10,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopBackward(nil, X[4], X[7])
		},
	},
	ProdTabEntry{
		String:     `Edge : "<" "-" "[" "*" int "]" "-"	<< ast.NewEdgeMultiHopBackward(nil, X[4], X[4]) >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      23,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeMultiHopBackward(nil, X[4], X[4])
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" "]" "-" ">"	<< ast.NewEdgeAnyForward() >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      24,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeAnyForward()
		},
	},
	ProdTabEntry{
		String:     `Edge : "-" "[" "]" "-"	<< ast.NewEdgeAny() >>`,
		Id:         "Edge",
		NTType:     5,
		Index:      25,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewEdgeAny()
		},
	},
	ProdTabEntry{
		String:     `ReturnClause : "RETURN" ReturnItems	<< ast.NewReturnClause(X[1]) >>`,
		Id:         "ReturnClause",
		NTType:     6,
		Index:      26,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnClause(X[1])
		},
	},
	ProdTabEntry{
		String:     `ReturnItems : ReturnItem	<< ast.NewReturnItems(X[0]) >>`,
		Id:         "ReturnItems",
		NTType:     7,
		Index:      27,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnItems(X[0])
		},
	},
	ProdTabEntry{
		String:     `ReturnItems : ReturnItems "," ReturnItem	<< ast.AppendReturnItem(X[0], X[2]) >>`,
		Id:         "ReturnItems",
		NTType:     7,
		Index:      28,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendReturnItem(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `ReturnItem : upid "(" id ")" "AS" id	<< ast.NewReturnAggregateWithAlias(X[0], X[2], X[5]) >>`,
		Id:         "ReturnItem",
		NTType:     8,
		Index:      29,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnAggregateWithAlias(X[0], X[2], X[5])
		},
	},
	ProdTabEntry{
		String:     `ReturnItem : upid "(" id ")"	<< ast.NewReturnAggregate(X[0], X[2]) >>`,
		Id:         "ReturnItem",
		NTType:     8,
		Index:      30,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnAggregate(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `ReturnItem : id "." id "AS" id	<< ast.NewReturnPropWithAlias(X[0], X[2], X[4]) >>`,
		Id:         "ReturnItem",
		NTType:     8,
		Index:      31,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnPropWithAlias(X[0], X[2], X[4])
		},
	},
	ProdTabEntry{
		String:     `ReturnItem : id "." id	<< ast.NewReturnProp(X[0], X[2]) >>`,
		Id:         "ReturnItem",
		NTType:     8,
		Index:      32,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnProp(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `ReturnItem : id	<< ast.NewReturnVar(X[0]) >>`,
		Id:         "ReturnItem",
		NTType:     8,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturnVar(X[0])
		},
	},
	ProdTabEntry{
		String:     `GroupByClause : "GROUP" "BY" GroupByItems	<< ast.NewGroupByClause(X[2]) >>`,
		Id:         "GroupByClause",
		NTType:     9,
		Index:      34,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewGroupByClause(X[2])
		},
	},
	ProdTabEntry{
		String:     `GroupByItems : GroupByItem	<< ast.NewGroupByItems(X[0]) >>`,
		Id:         "GroupByItems",
		NTType:     10,
		Index:      35,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewGroupByItems(X[0])
		},
	},
	ProdTabEntry{
		String:     `GroupByItems : GroupByItems "," GroupByItem	<< ast.AppendGroupByItem(X[0], X[2]) >>`,
		Id:         "GroupByItems",
		NTType:     10,
		Index:      36,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendGroupByItem(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `GroupByItem : id "." id	<< ast.NewGroupByItem(X[0], X[2]) >>`,
		Id:         "GroupByItem",
		NTType:     11,
		Index:      37,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewGroupByItem(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `OrderByClause : "ORDER" "BY" OrderByItems	<< ast.NewOrderByClause(X[2]) >>`,
		Id:         "OrderByClause",
		NTType:     12,
		Index:      38,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewOrderByClause(X[2])
		},
	},
	ProdTabEntry{
		String:     `OrderByItems : OrderByItem	<< ast.NewOrderByItems(X[0]) >>`,
		Id:         "OrderByItems",
		NTType:     13,
		Index:      39,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewOrderByItems(X[0])
		},
	},
	ProdTabEntry{
		String:     `OrderByItems : OrderByItems "," OrderByItem	<< ast.AppendOrderByItem(X[0], X[2]) >>`,
		Id:         "OrderByItems",
		NTType:     13,
		Index:      40,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendOrderByItem(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `OrderByItem : id "ASC"	<< ast.NewOrderByItemAsc(X[0]) >>`,
		Id:         "OrderByItem",
		NTType:     14,
		Index:      41,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewOrderByItemAsc(X[0])
		},
	},
	ProdTabEntry{
		String:     `OrderByItem : id "DESC"	<< ast.NewOrderByItemDesc(X[0]) >>`,
		Id:         "OrderByItem",
		NTType:     14,
		Index:      42,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewOrderByItemDesc(X[0])
		},
	},
	ProdTabEntry{
		String:     `OrderByItem : id	<< ast.NewOrderByItem(X[0]) >>`,
		Id:         "OrderByItem",
		NTType:     14,
		Index:      43,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewOrderByItem(X[0])
		},
	},
	ProdTabEntry{
		String:     `LimitClause : "LIMIT" int	<< ast.NewLimitClause(X[1]) >>`,
		Id:         "LimitClause",
		NTType:     15,
		Index:      44,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewLimitClause(X[1])
		},
	},
}
