// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/wouteroostervld/chainsaw/pkg/cypher/token"
)

const (
	NoState    = -1
	NumStates  = 54
	NumSymbols = 68
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '_'
1: '_'
2: 'M'
3: 'A'
4: 'T'
5: 'C'
6: 'H'
7: '('
8: ':'
9: ')'
10: '-'
11: '['
12: ']'
13: '>'
14: '*'
15: '.'
16: '<'
17: 'R'
18: 'E'
19: 'T'
20: 'U'
21: 'R'
22: 'N'
23: ','
24: 'A'
25: 'S'
26: 'G'
27: 'R'
28: 'O'
29: 'U'
30: 'P'
31: 'B'
32: 'Y'
33: 'O'
34: 'R'
35: 'D'
36: 'E'
37: 'R'
38: 'A'
39: 'S'
40: 'C'
41: 'D'
42: 'E'
43: 'S'
44: 'C'
45: 'L'
46: 'I'
47: 'M'
48: 'I'
49: 'T'
50: ' '
51: '\t'
52: '\n'
53: '\r'
54: '/'
55: '/'
56: '\n'
57: 'a'-'z'
58: 'a'-'z'
59: 'A'-'Z'
60: '0'-'9'
61: 'A'-'Z'
62: 'a'-'z'
63: 'A'-'Z'
64: '0'-'9'
65: '0'-'9'
66: '0'-'9'
67: .
*/
