// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 40: // ['(','(']
			return 2
		case r == 41: // [')',')']
			return 3
		case r == 42: // ['*','*']
			return 4
		case r == 44: // [',',',']
			return 5
		case r == 45: // ['-','-']
			return 6
		case r == 46: // ['.','.']
			return 7
		case r == 47: // ['/','/']
			return 8
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		case r == 58: // [':',':']
			return 10
		case r == 60: // ['<','<']
			return 11
		case r == 62: // ['>','>']
			return 12
		case r == 65: // ['A','A']
			return 13
		case r == 66: // ['B','B']
			return 14
		case r == 67: // ['C','C']
			return 15
		case r == 68: // ['D','D']
			return 16
		case 69 <= r && r <= 70: // ['E','F']
			return 15
		case r == 71: // ['G','G']
			return 17
		case 72 <= r && r <= 75: // ['H','K']
			return 15
		case r == 76: // ['L','L']
			return 18
		case r == 77: // ['M','M']
			return 19
		case r == 78: // ['N','N']
			return 15
		case r == 79: // ['O','O']
			return 20
		case 80 <= r && r <= 81: // ['P','Q']
			return 15
		case r == 82: // ['R','R']
			return 21
		case 83 <= r && r <= 90: // ['S','Z']
			return 15
		case r == 91: // ['[','[']
			return 22
		case r == 93: // [']',']']
			return 23
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 25
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 82: // ['A','R']
			return 15
		case r == 83: // ['S','S']
			return 26
		case 84 <= r && r <= 90: // ['T','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 88: // ['A','X']
			return 15
		case r == 89: // ['Y','Y']
			return 27
		case r == 90: // ['Z','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 68: // ['A','D']
			return 15
		case r == 69: // ['E','E']
			return 28
		case 70 <= r && r <= 90: // ['F','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 81: // ['A','Q']
			return 15
		case r == 82: // ['R','R']
			return 29
		case 83 <= r && r <= 90: // ['S','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 72: // ['A','H']
			return 15
		case r == 73: // ['I','I']
			return 30
		case 74 <= r && r <= 90: // ['J','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 65: // ['A','A']
			return 31
		case 66 <= r && r <= 90: // ['B','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 81: // ['A','Q']
			return 15
		case r == 82: // ['R','R']
			return 32
		case 83 <= r && r <= 90: // ['S','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 68: // ['A','D']
			return 15
		case r == 69: // ['E','E']
			return 33
		case 70 <= r && r <= 90: // ['F','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 24
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 24
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 34
		default:
			return 25
		}
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 66: // ['A','B']
			return 15
		case r == 67: // ['C','C']
			return 35
		case 68 <= r && r <= 90: // ['D','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 82: // ['A','R']
			return 15
		case r == 83: // ['S','S']
			return 36
		case 84 <= r && r <= 90: // ['T','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 78: // ['A','N']
			return 15
		case r == 79: // ['O','O']
			return 37
		case 80 <= r && r <= 90: // ['P','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 76: // ['A','L']
			return 15
		case r == 77: // ['M','M']
			return 38
		case 78 <= r && r <= 90: // ['N','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 83: // ['A','S']
			return 15
		case r == 84: // ['T','T']
			return 39
		case 85 <= r && r <= 90: // ['U','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 67: // ['A','C']
			return 15
		case r == 68: // ['D','D']
			return 40
		case 69 <= r && r <= 90: // ['E','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 83: // ['A','S']
			return 15
		case r == 84: // ['T','T']
			return 41
		case 85 <= r && r <= 90: // ['U','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 66: // ['A','B']
			return 15
		case r == 67: // ['C','C']
			return 42
		case 68 <= r && r <= 90: // ['D','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 84: // ['A','T']
			return 15
		case r == 85: // ['U','U']
			return 43
		case 86 <= r && r <= 90: // ['V','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 72: // ['A','H']
			return 15
		case r == 73: // ['I','I']
			return 44
		case 74 <= r && r <= 90: // ['J','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 66: // ['A','B']
			return 15
		case r == 67: // ['C','C']
			return 45
		case 68 <= r && r <= 90: // ['D','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 68: // ['A','D']
			return 15
		case r == 69: // ['E','E']
			return 46
		case 70 <= r && r <= 90: // ['F','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 84: // ['A','T']
			return 15
		case r == 85: // ['U','U']
			return 47
		case 86 <= r && r <= 90: // ['V','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 79: // ['A','O']
			return 15
		case r == 80: // ['P','P']
			return 48
		case 81 <= r && r <= 90: // ['Q','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 83: // ['A','S']
			return 15
		case r == 84: // ['T','T']
			return 49
		case 85 <= r && r <= 90: // ['U','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 71: // ['A','G']
			return 15
		case r == 72: // ['H','H']
			return 50
		case 73 <= r && r <= 90: // ['I','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 81: // ['A','Q']
			return 15
		case r == 82: // ['R','R']
			return 51
		case 83 <= r && r <= 90: // ['S','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 81: // ['A','Q']
			return 15
		case r == 82: // ['R','R']
			return 52
		case 83 <= r && r <= 90: // ['S','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 77: // ['A','M']
			return 15
		case r == 78: // ['N','N']
			return 53
		case 79 <= r && r <= 90: // ['O','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
}
